# Generated by Django 5.2 on 2025-06-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkDescription',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mapping.park')),
                ('description', models.TextField()),
                ('address', models.CharField(blank=True, help_text='Full address of the park', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='park_images/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
